# Generated by Django 5.0.7 on 2024-07-29 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_reset_password_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+999999999'. Допускается до 14 цифр.", regex='^\\+?1?\\d{9,14}$')], verbose_name='Номер телефона'),
        ),
    ]
